site_name: Causal Lab AIF Documentation
repo_url: https://github.com/Songeo/causal-lab-aif
repo_name: Causal Lab AIF

nav:
    - Home: index.md

theme:
    name: material
    logo: 'img/ai.png'
    favicon: 'img/ai.png'
    palette:
        -   scheme: bbva
            toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to dark mode
        -   scheme: slate
            primary: indigo
            accent: indigo
            toggle:
                icon: material/toggle-switch
                name: Switch to light mode
    features:
        - navigation.tracking
        - navigation.top
        - navigation.indexes
        - instant
        - tabs
        - search.highlight
        - content.code.copy
    icon:
      logo: material/book-open-page-variant
      repo: fontawesome/brands/github
      alternate: fontawesome/solid/earth-europe

site_dir: site

extra_css:
  - stylesheets/extra.css

extra_javascript:
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    analytics:
        provider: google
        property: G-479XP8YGJJ
    consent:
        title: Cookie consent
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
    social:
        - icon: fontawesome/regular/envelope
          link: https://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&to=migueldaygoro.grados@bbva.com
          name: Contact us on Gmail!
    version:
        provider: mike
        default: latest

markdown_extensions:
   - abbr
   - admonition
   - attr_list
   - codehilite
   - def_list
   - footnotes
   - meta
   - toc:
       permalink: true
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.betterem:
       smart_enable: all
   - pymdownx.caret
   - pymdownx.critic
   - pymdownx.details
   - pymdownx.highlight
   - pymdownx.inlinehilite
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.snippets:
       check_paths: true
   - pymdownx.superfences:
       custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tabbed
   - pymdownx.tilde
   - pymdownx.tasklist:
        clickable_checkbox: true
        custom_checkbox: false
   - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search
    - autorefs
    - mkdocstrings
    - mike:
        canonical_version: null
        version_selector: true
        css_dir: stylesheets
        javascript_dir: javascripts
    - print-site:
        path_to_pdf: "assets/the_name_of_your_file.pdf"
